### ISSUE TITLE
Does the decode_utf16 just consider the utf16_BE?

### ISSUE THREAD

**Issue by BaccanoEva** [Davipb/utf8-utf16-converter#2]
It seems like the decode_utf16 function just consider utf16_LE, how about utf16_BE?

**Comment by Davipb** [comment]
The converter code is actually endianness-agnostic, since it treats UTF-16 characters as regular 16-bit numbers. 

The choice of what endianness to use depends on how you transform your source bytes (e.g. a file) into 16-bit numbers. The tester program currently does a blind pointer conversion for that, so it follows whatever endianness your computer uses (which in most machines is Little-Endian, so that's what I wrote in the tester's documentation).
